---
title: "Final Project Cleaning"
authors: "Anna Livingstone Nate Groves"
date: "Fall 2025"
output:
  pdf_document:
    number_sections: no
    toc: false
    toc_depth: 1
  html_document:
    df_print: paged
    number_sections: no
    toc: false
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

importing each set of data
```{r}

circulation <- drop_na(read_csv("../data/library_circulation.csv"))
demographics <- drop_na(read_csv("../data/library_demographics.csv"))
electronic <- read_csv("../data/library_electronic.csv")%>%
              filter(is.na(`Suppression Note`)) %>% # This only exists if data is missing, so we can drop it to make our lives easier
              select(-(`Suppression Note`)) %>%
              drop_na()
programs <- drop_na(read_csv("../data/library_programs.csv"))
revenue <- read_csv("../data/library_revenue.csv") %>%
              filter(is.na(`Suppression Note`)) %>% # This only exists if data is missing, so we can drop it to make our lives easier
              select(-(`Suppression Note`)) %>%
              drop_na()
services <- drop_na(read_csv("../data/library_services.csv"))

```

joining data together (some weird quirks in the data, but this shouldn't change anything just make column names cleaner)
```{r}
libraries <- inner_join(circulation, demographics, by = c("FSCS Key", "Library Name", "Service Area Population", "Locale"))
libraries <- inner_join(libraries, electronic, by = c("FSCS Key", "Library Name", "Service Area Population", "Locale"))
libraries <- inner_join(libraries, programs, by = c("FSCS Key", "Library Name", "Service Area Population", "Locale"))
libraries <- inner_join(libraries, revenue, by = c("FSCS Key", "Library Name", "Service Area Population", "Locale"))
libraries <- inner_join(libraries, services, by = c("FSCS Key", "Library Name", "Service Area Population", "Locale"))
```

removing all negative numbers which mean missing values and saving
and adding some columns which are more useful
```{r}
libraries_filtered <- libraries %>%
     filter(if_all(where(is.numeric), ~ . >= 0)) %>%
      mutate(state = str_sub(`FSCS Key`, 1, 2)) %>%
      select(-c(`FSCS Key`, `Library Name`, `Total Library Programs`, `Total Revenue ($)`, `Electronic Material Circulation`, `Print Material Circulation`, `Other Physical Item Circulation`, `Total Program Attendance`, )) %>%
      select(state, everything(), `Total Circulation` = `Total Circulation`)
set.seed(13)
smp_size <- floor(0.8 * nrow(libraries_filtered)) # 80% for training
train_indices <- sample(seq_len(nrow(libraries_filtered)), size = smp_size)
train_data <- libraries_filtered[train_indices, ]
test_data <- libraries_filtered[-train_indices, ] # Remaining rows for testing
write.csv(train_data, "../data/libraries.csv", row.names = FALSE)
write.csv(test_data, "../data/libraries_testing.cdv", row.names = FALSE)
```

Show the final file:
```{r}
show(libraries_filtered)
```

